import createClient, { type Client, type Middleware } from "openapi-fetch";
import type { paths, components } from "./types.gen.js"; // generated by openapi-typescript
import type { DoFn } from "./http.js";
import { createProductsResource } from "./resources/products.js";
import { createBrandsResource } from "./resources/brands.js";
import { createCategoriesResource } from "./resources/categories.js";
import { createLocationsResource } from "./resources/locations.js";
import { createInventoryResource } from "./resources/inventory.js";

export type Product = components["schemas"]["Product"];
export type ProductDetail = components["schemas"]["ProductDetail"];
export type ProductVariant = components["schemas"]["ProductVariant"];
export type ProductOption = components["schemas"]["ProductOption"];
export type CreateVariantsDto = components["schemas"]["CreateVariantsDto"];
export type Brand = components["schemas"]["Brand"];
export type Category = components["schemas"]["Category"];
export type Location = components["schemas"]["Location"];
export type InventoryRecord = components["schemas"]["InventoryRecord"];
export type InventoryMovementRecord = components["schemas"]["InventoryMovementRecord"];

export class AdminClient {
  accessToken: string | undefined;
  client: Client<paths>;

  products: ReturnType<typeof createProductsResource>;
  brands: ReturnType<typeof createBrandsResource>;
  categories: ReturnType<typeof createCategoriesResource>;
  locations: ReturnType<typeof createLocationsResource>;
  inventory: ReturnType<typeof createInventoryResource>;

  // every request needs the bearer token and the cross-origin cookie
  // (for the refresh_token) — centralized here instead of at each call site.
  // Request.headers is mutable in place, but credentials isn't, so that part
  // has to go through a rebuilt Request.
  private authMiddleware: Middleware = {
    onRequest: ({ request }) => {
      request.headers.set("Authorization", `Bearer ${this.accessToken}`);
      return new Request(request, { credentials: "include" });
    },
  };

  constructor(baseUrl: string) {
    this.client = createClient({ baseUrl });
    this.client.use(this.authMiddleware);

    const doRequest: DoFn = (request) => this.do(request);

    this.products = createProductsResource(this.client, doRequest);
    this.brands = createBrandsResource(this.client, doRequest);
    this.categories = createCategoriesResource(this.client, doRequest);
    this.locations = createLocationsResource(this.client, doRequest);
    this.inventory = createInventoryResource(this.client, doRequest);
  }

  async signIn(credentials: components["schemas"]["SignInDto"]) {
    const { data } = await this.client.POST("/auth/signin", {
      body: credentials,
    });

    this.accessToken = data?.access_token;
    return this.accessToken;
  }

  async signUp(signup: components["schemas"]["SignUpDto"]) {
    const { data } = await this.client.POST("/auth/signup", {
      body: signup,
    });

    this.accessToken = data?.access_token;
    return this.accessToken;
  }

  async refreshAccessToken() {
    const { data } = await this.client.GET("/auth/token/refresh");
    this.accessToken = data?.access_token;
    return this.accessToken;
  }

  // request is a thunk so the retry rebuilds headers off the refreshed accessToken, not a stale one
  private async do<T>(
    request: () => Promise<{ data?: T; error?: unknown; response: Response }>,
  ) {
    const result = await request();
    if (result.response.status === 401) {
      await this.refreshAccessToken();
      return await request();
    }
    return result;
  }
}
