import createClient, { type Client } from "openapi-fetch";
import type { paths, components } from "./types.gen.js"; // generated by openapi-typescript

export type Product = components["schemas"]["Product"];
export type ProductDetail = components["schemas"]["ProductDetail"];
export type ProductVariant = components["schemas"]["ProductVariant"];
export type ProductOption = components["schemas"]["ProductOption"];
export type CreateVariantsDto = components["schemas"]["CreateVariantsDto"];
export type Brand = components["schemas"]["Brand"];
export type Category = components["schemas"]["Category"];
export type Location = components["schemas"]["Location"];
export type InventoryRecord = components["schemas"]["InventoryRecord"];
export type InventoryMovementRecord = components["schemas"]["InventoryMovementRecord"];

export class AdminClient {
  accessToken: string | undefined;
  client: Client<paths>;

  constructor(baseUrl: string) {
    this.client = createClient({ baseUrl });
  }

  async signIn(credentials: components["schemas"]["SignInDto"]) {
    // credentials: "include" so the backend's refresh_token cookie is stored;
    // without it the browser drops the cross-origin Set-Cookie response
    const { data } = await this.client.POST("/auth/signin", {
      body: credentials,
      credentials: "include",
    });

    this.accessToken = data?.access_token;
    return this.accessToken;
  }

  async refreshAccessToken() {
    const { data } = await this.client.GET("/auth/token/refresh", {
      credentials: "include",
    });
    this.accessToken = data?.access_token;
    return this.accessToken;
  }

  // request is a thunk so the retry rebuilds headers off the refreshed accessToken, not a stale one
  private async do<T>(
    request: () => Promise<{ data?: T; error?: unknown; response: Response }>,
  ) {
    const result = await request();
    if (result.response.status === 401) {
      await this.refreshAccessToken();
      return await request();
    }
    return result;
  }

  products = {
    list: async () => {
      const { data } = await this.do(() =>
        this.client.GET("/products", {
          credentials: "include",
          headers: {
            Authorization: `Bearer ${this.accessToken}`,
          },
        }),
      );
      return data;
    },

    create: async (params: components["schemas"]["CreateProductDto"]) => {
      const { data } = await this.do(() => {
        return this.client.POST("/products", {
          body: params,
          credentials: "include",
          headers: {
            Authorization: `Bearer ${this.accessToken}`,
          },
        });
      });
      return data;
    },

    getById: async (id: number) => {
      const path: paths["/products/{id}"]["get"]["parameters"]["path"] = {
        id: String(id),
      };
      const { data } = await this.do(() =>
        this.client.GET("/products/{id}", {
          params: { path },
          credentials: "include",
          headers: {
            Authorization: `Bearer ${this.accessToken}`,
          },
        }),
      );
      return data;
    },

    update: async (
      id: number,
      params: components["schemas"]["UpdateProductDto"],
    ) => {
      const path: paths["/products/{id}"]["patch"]["parameters"]["path"] = {
        id: String(id),
      };
      const { data } = await this.do(() =>
        this.client.PATCH("/products/{id}", {
          params: { path },
          body: params,
          credentials: "include",
          headers: {
            Authorization: `Bearer ${this.accessToken}`,
          },
        }),
      );
      return data;
    },

    remove: async (id: number) => {
      const path: paths["/products/{id}"]["delete"]["parameters"]["path"] = {
        id: String(id),
      };
      const { data } = await this.do(() =>
        this.client.DELETE("/products/{id}", {
          params: { path },
          credentials: "include",
          headers: {
            Authorization: `Bearer ${this.accessToken}`,
          },
        }),
      );
      return data;
    },

    variants: {
      list: async (productId: number) => {
        const path: paths["/products/{id}/variants"]["get"]["parameters"]["path"] =
          {
            id: String(productId),
          };
        const { data } = await this.do(() =>
          this.client.GET("/products/{id}/variants", {
            params: { path },
            credentials: "include",
            headers: {
              Authorization: `Bearer ${this.accessToken}`,
            },
          }),
        );
        return data;
      },

      create: async (
        productId: number,
        params: components["schemas"]["CreateVariantsDto"],
      ) => {
        const path: paths["/products/{id}/variants"]["post"]["parameters"]["path"] =
          {
            id: String(productId),
          };
        const { data } = await this.do(() =>
          this.client.POST("/products/{id}/variants", {
            params: { path },
            body: params,
            credentials: "include",
            headers: {
              Authorization: `Bearer ${this.accessToken}`,
            },
          }),
        );
        return data;
      },

      update: async (
        productId: number,
        variantId: number,
        params: components["schemas"]["UpdateVariantDto"],
      ) => {
        const path: paths["/products/{id}/variants/{variantId}"]["patch"]["parameters"]["path"] =
          {
            id: String(productId),
            variantId: String(variantId),
          };
        const { data } = await this.do(() =>
          this.client.PATCH("/products/{id}/variants/{variantId}", {
            params: { path },
            body: params,
            credentials: "include",
            headers: {
              Authorization: `Bearer ${this.accessToken}`,
            },
          }),
        );
        return data;
      },
    },

    options: {
      list: async (productId: number) => {
        const path: paths["/products/{id}/options"]["get"]["parameters"]["path"] =
          {
            id: String(productId),
          };
        const { data } = await this.do(() =>
          this.client.GET("/products/{id}/options", {
            params: { path },
            credentials: "include",
            headers: {
              Authorization: `Bearer ${this.accessToken}`,
            },
          }),
        );
        return data;
      },

      update: async (
        productId: number,
        optionId: number,
        params: components["schemas"]["UpdateProductOptionDto"],
      ) => {
        const path: paths["/products/{id}/options/{optionId}"]["patch"]["parameters"]["path"] =
          {
            id: String(productId),
            optionId: String(optionId),
          };
        const { data } = await this.do(() =>
          this.client.PATCH("/products/{id}/options/{optionId}", {
            params: { path },
            body: params,
            credentials: "include",
            headers: {
              Authorization: `Bearer ${this.accessToken}`,
            },
          }),
        );
        return data;
      },

      remove: async (productId: number, optionId: number) => {
        const path: paths["/products/{id}/options/{optionId}"]["delete"]["parameters"]["path"] =
          {
            id: String(productId),
            optionId: String(optionId),
          };
        const { data } = await this.do(() =>
          this.client.DELETE("/products/{id}/options/{optionId}", {
            params: { path },
            credentials: "include",
            headers: {
              Authorization: `Bearer ${this.accessToken}`,
            },
          }),
        );
        return data;
      },

      values: {
        remove: async (productId: number, optionId: number, valueId: number) => {
          const path: paths["/products/{id}/options/{optionId}/values/{valueId}"]["delete"]["parameters"]["path"] =
            {
              id: String(productId),
              optionId: String(optionId),
              valueId: String(valueId),
            };
          const { data } = await this.do(() =>
            this.client.DELETE(
              "/products/{id}/options/{optionId}/values/{valueId}",
              {
                params: { path },
                credentials: "include",
                headers: {
                  Authorization: `Bearer ${this.accessToken}`,
                },
              },
            ),
          );
          return data;
        },
      },
    },
  };

  brands = {
    list: async () => {
      const { data } = await this.do(() =>
        this.client.GET("/brands", {
          credentials: "include",
          headers: {
            Authorization: `Bearer ${this.accessToken}`,
          },
        }),
      );
      return data;
    },

    create: async (params: components["schemas"]["CreateBrandDto"]) => {
      const { data } = await this.do(() =>
        this.client.POST("/brands", {
          body: params,
          credentials: "include",
          headers: {
            Authorization: `Bearer ${this.accessToken}`,
          },
        }),
      );
      return data;
    },
  };

  categories = {
    list: async () => {
      const { data } = await this.do(() =>
        this.client.GET("/categories", {
          credentials: "include",
          headers: {
            Authorization: `Bearer ${this.accessToken}`,
          },
        }),
      );
      return data;
    },

    create: async (params: components["schemas"]["CreateCategoryDto"]) => {
      const { data } = await this.do(() =>
        this.client.POST("/categories", {
          body: params,
          credentials: "include",
          headers: {
            Authorization: `Bearer ${this.accessToken}`,
          },
        }),
      );
      return data;
    },
  };

  locations = {
    list: async () => {
      const { data } = await this.do(() =>
        this.client.GET("/locations", {
          credentials: "include",
          headers: {
            Authorization: `Bearer ${this.accessToken}`,
          },
        }),
      );
      return data;
    },

    create: async (params: components["schemas"]["CreateLocationDto"]) => {
      const { data } = await this.do(() =>
        this.client.POST("/locations", {
          body: params,
          credentials: "include",
          headers: {
            Authorization: `Bearer ${this.accessToken}`,
          },
        }),
      );
      return data;
    },
  };

  inventory = {
    list: async () => {
      const { data } = await this.do(() =>
        this.client.GET("/inventory", {
          credentials: "include",
          headers: {
            Authorization: `Bearer ${this.accessToken}`,
          },
        }),
      );
      return data;
    },

    movements: {
      list: async () => {
        const { data } = await this.do(() =>
          this.client.GET("/inventory/movements", {
            credentials: "include",
            headers: {
              Authorization: `Bearer ${this.accessToken}`,
            },
          }),
        );
        return data;
      },

      create: async (
        params: components["schemas"]["CreateInventoryMovementDto"],
      ) => {
        const { data } = await this.do(() =>
          this.client.POST("/inventory/movements", {
            body: params,
            credentials: "include",
            headers: {
              Authorization: `Bearer ${this.accessToken}`,
            },
          }),
        );
        return data;
      },
    },
  };
}
