import createClient, { type Client, type Middleware } from "openapi-fetch";
import type { paths, components } from "./types.gen.js"; // generated by openapi-typescript

export type PosCatalogPage = components["schemas"]["PosCatalogPage"];
export type PosCatalogProduct = components["schemas"]["PosCatalogProduct"];
export type PosCatalogVariant = components["schemas"]["PosCatalogVariant"];
export type PosScanResult = components["schemas"]["PosScanResult"];
export type PosSession = components["schemas"]["PosSession"];
export type PairingResult = components["schemas"]["PairingResult"];

const DEVICE_TOKEN_HEADER = "x-pos-device-token";

export type CatalogQuery = NonNullable<
  paths["/pos/catalog"]["get"]["parameters"]["query"]
>;

// The device token is owned by the caller (the POS app keeps it in secure
// storage). Pass a getter so a token set after construction — e.g. right
// after pair() — takes effect on the next request without rebuilding.
export class PosClient {
  client: Client<paths>;

  private tokenMiddleware: Middleware = {
    onRequest: ({ request }) => {
      const token = this.getToken();
      if (token) request.headers.set(DEVICE_TOKEN_HEADER, token);
      return request;
    },
  };

  constructor(
    baseUrl: string,
    private readonly getToken: () => string | undefined = () => undefined,
  ) {
    this.client = createClient({ baseUrl });
    this.client.use(this.tokenMiddleware);
  }

  // no token yet at this point — the response carries the one to store
  async pair(pairingCode: string): Promise<PairingResult | undefined> {
    const { data } = await this.client.POST("/pos/pair", {
      body: { pairingCode },
    });
    return data;
  }

  async session(): Promise<PosSession | undefined> {
    const { data } = await this.client.GET("/pos/session");
    return data;
  }

  catalog = {
    list: async (query: CatalogQuery = {}): Promise<PosCatalogPage | undefined> => {
      const { data } = await this.client.GET("/pos/catalog", {
        params: { query },
      });
      return data;
    },

    scan: async (code: string): Promise<PosScanResult | undefined> => {
      const { data } = await this.client.GET("/pos/catalog/scan", {
        params: { query: { code } },
      });
      return data;
    },

    getById: async (id: number): Promise<PosCatalogProduct | undefined> => {
      const { data } = await this.client.GET("/pos/catalog/{id}", {
        params: { path: { id } },
      });
      return data;
    },
  };
}
