/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProductsIndexRouteImport } from './routes/app/products/index'
import { Route as AppProductsCreateRouteImport } from './routes/app/products/create'
import { Route as AppProductsIdRouteImport } from './routes/app/products/$id'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsCreateRoute = AppProductsCreateRouteImport.update({
  id: '/products/create',
  path: '/products/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsIdRoute = AppProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/signin': typeof SigninRoute
  '/app/products/$id': typeof AppProductsIdRoute
  '/app/products/create': typeof AppProductsCreateRoute
  '/app/products/': typeof AppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/signin': typeof SigninRoute
  '/app/products/$id': typeof AppProductsIdRoute
  '/app/products/create': typeof AppProductsCreateRoute
  '/app/products': typeof AppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/signin': typeof SigninRoute
  '/app/products/$id': typeof AppProductsIdRoute
  '/app/products/create': typeof AppProductsCreateRoute
  '/app/products/': typeof AppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/inventory'
    | '/signin'
    | '/app/products/$id'
    | '/app/products/create'
    | '/app/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/inventory'
    | '/signin'
    | '/app/products/$id'
    | '/app/products/create'
    | '/app/products'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/inventory'
    | '/signin'
    | '/app/products/$id'
    | '/app/products/create'
    | '/app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  InventoryRoute: typeof InventoryRoute
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/products/': {
      id: '/app/products/'
      path: '/products'
      fullPath: '/app/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/products/create': {
      id: '/app/products/create'
      path: '/products/create'
      fullPath: '/app/products/create'
      preLoaderRoute: typeof AppProductsCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/products/$id': {
      id: '/app/products/$id'
      path: '/products/$id'
      fullPath: '/app/products/$id'
      preLoaderRoute: typeof AppProductsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppProductsIdRoute: typeof AppProductsIdRoute
  AppProductsCreateRoute: typeof AppProductsCreateRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProductsIdRoute: AppProductsIdRoute,
  AppProductsCreateRoute: AppProductsCreateRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  InventoryRoute: InventoryRoute,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
