/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProductsRouteRouteImport } from './routes/app/products/route'
import { Route as AppUsersIndexRouteImport } from './routes/app/users/index'
import { Route as AppRolesIndexRouteImport } from './routes/app/roles/index'
import { Route as AppProductsIndexRouteImport } from './routes/app/products/index'
import { Route as AppOrdersIndexRouteImport } from './routes/app/orders/index'
import { Route as AppLocationsIndexRouteImport } from './routes/app/locations/index'
import { Route as AppInventoryIndexRouteImport } from './routes/app/inventory/index'
import { Route as AppCustomersIndexRouteImport } from './routes/app/customers/index'
import { Route as AppProductsCreateRouteImport } from './routes/app/products/create'
import { Route as AppProductsIdRouteImport } from './routes/app/products/$id'
import { Route as AppLocationsCreateRouteImport } from './routes/app/locations/create'
import { Route as AppProductsCategoriesIndexRouteImport } from './routes/app/products/categories/index'
import { Route as AppProductsBrandsIndexRouteImport } from './routes/app/products/brands/index'
import { Route as AppProductsCategoriesCreateRouteImport } from './routes/app/products/categories/create'
import { Route as AppProductsBrandsCreateRouteImport } from './routes/app/products/brands/create'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProductsRouteRoute = AppProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRolesIndexRoute = AppRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProductsRouteRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLocationsIndexRoute = AppLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsCreateRoute = AppProductsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppProductsRouteRoute,
} as any)
const AppProductsIdRoute = AppProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProductsRouteRoute,
} as any)
const AppLocationsCreateRoute = AppLocationsCreateRouteImport.update({
  id: '/locations/create',
  path: '/locations/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsCategoriesIndexRoute =
  AppProductsCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AppProductsRouteRoute,
  } as any)
const AppProductsBrandsIndexRoute = AppProductsBrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => AppProductsRouteRoute,
} as any)
const AppProductsCategoriesCreateRoute =
  AppProductsCategoriesCreateRouteImport.update({
    id: '/categories/create',
    path: '/categories/create',
    getParentRoute: () => AppProductsRouteRoute,
  } as any)
const AppProductsBrandsCreateRoute = AppProductsBrandsCreateRouteImport.update({
  id: '/brands/create',
  path: '/brands/create',
  getParentRoute: () => AppProductsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/signin': typeof SigninRoute
  '/app/products': typeof AppProductsRouteRouteWithChildren
  '/app/locations/create': typeof AppLocationsCreateRoute
  '/app/products/$id': typeof AppProductsIdRoute
  '/app/products/create': typeof AppProductsCreateRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/inventory/': typeof AppInventoryIndexRoute
  '/app/locations/': typeof AppLocationsIndexRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/roles/': typeof AppRolesIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
  '/app/products/brands/create': typeof AppProductsBrandsCreateRoute
  '/app/products/categories/create': typeof AppProductsCategoriesCreateRoute
  '/app/products/brands/': typeof AppProductsBrandsIndexRoute
  '/app/products/categories/': typeof AppProductsCategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/signin': typeof SigninRoute
  '/app/locations/create': typeof AppLocationsCreateRoute
  '/app/products/$id': typeof AppProductsIdRoute
  '/app/products/create': typeof AppProductsCreateRoute
  '/app/customers': typeof AppCustomersIndexRoute
  '/app/inventory': typeof AppInventoryIndexRoute
  '/app/locations': typeof AppLocationsIndexRoute
  '/app/orders': typeof AppOrdersIndexRoute
  '/app/products': typeof AppProductsIndexRoute
  '/app/roles': typeof AppRolesIndexRoute
  '/app/users': typeof AppUsersIndexRoute
  '/app/products/brands/create': typeof AppProductsBrandsCreateRoute
  '/app/products/categories/create': typeof AppProductsCategoriesCreateRoute
  '/app/products/brands': typeof AppProductsBrandsIndexRoute
  '/app/products/categories': typeof AppProductsCategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/signin': typeof SigninRoute
  '/app/products': typeof AppProductsRouteRouteWithChildren
  '/app/locations/create': typeof AppLocationsCreateRoute
  '/app/products/$id': typeof AppProductsIdRoute
  '/app/products/create': typeof AppProductsCreateRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/inventory/': typeof AppInventoryIndexRoute
  '/app/locations/': typeof AppLocationsIndexRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/roles/': typeof AppRolesIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
  '/app/products/brands/create': typeof AppProductsBrandsCreateRoute
  '/app/products/categories/create': typeof AppProductsCategoriesCreateRoute
  '/app/products/brands/': typeof AppProductsBrandsIndexRoute
  '/app/products/categories/': typeof AppProductsCategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/inventory'
    | '/signin'
    | '/app/products'
    | '/app/locations/create'
    | '/app/products/$id'
    | '/app/products/create'
    | '/app/customers/'
    | '/app/inventory/'
    | '/app/locations/'
    | '/app/orders/'
    | '/app/products/'
    | '/app/roles/'
    | '/app/users/'
    | '/app/products/brands/create'
    | '/app/products/categories/create'
    | '/app/products/brands/'
    | '/app/products/categories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/inventory'
    | '/signin'
    | '/app/locations/create'
    | '/app/products/$id'
    | '/app/products/create'
    | '/app/customers'
    | '/app/inventory'
    | '/app/locations'
    | '/app/orders'
    | '/app/products'
    | '/app/roles'
    | '/app/users'
    | '/app/products/brands/create'
    | '/app/products/categories/create'
    | '/app/products/brands'
    | '/app/products/categories'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/inventory'
    | '/signin'
    | '/app/products'
    | '/app/locations/create'
    | '/app/products/$id'
    | '/app/products/create'
    | '/app/customers/'
    | '/app/inventory/'
    | '/app/locations/'
    | '/app/orders/'
    | '/app/products/'
    | '/app/roles/'
    | '/app/users/'
    | '/app/products/brands/create'
    | '/app/products/categories/create'
    | '/app/products/brands/'
    | '/app/products/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  InventoryRoute: typeof InventoryRoute
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/users/': {
      id: '/app/users/'
      path: '/users'
      fullPath: '/app/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/roles/': {
      id: '/app/roles/'
      path: '/roles'
      fullPath: '/app/roles/'
      preLoaderRoute: typeof AppRolesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/products/': {
      id: '/app/products/'
      path: '/'
      fullPath: '/app/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/app/orders/': {
      id: '/app/orders/'
      path: '/orders'
      fullPath: '/app/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/locations/': {
      id: '/app/locations/'
      path: '/locations'
      fullPath: '/app/locations/'
      preLoaderRoute: typeof AppLocationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inventory/': {
      id: '/app/inventory/'
      path: '/inventory'
      fullPath: '/app/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/customers/': {
      id: '/app/customers/'
      path: '/customers'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/products/create': {
      id: '/app/products/create'
      path: '/create'
      fullPath: '/app/products/create'
      preLoaderRoute: typeof AppProductsCreateRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/app/products/$id': {
      id: '/app/products/$id'
      path: '/$id'
      fullPath: '/app/products/$id'
      preLoaderRoute: typeof AppProductsIdRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/app/locations/create': {
      id: '/app/locations/create'
      path: '/locations/create'
      fullPath: '/app/locations/create'
      preLoaderRoute: typeof AppLocationsCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/products/categories/': {
      id: '/app/products/categories/'
      path: '/categories'
      fullPath: '/app/products/categories/'
      preLoaderRoute: typeof AppProductsCategoriesIndexRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/app/products/brands/': {
      id: '/app/products/brands/'
      path: '/brands'
      fullPath: '/app/products/brands/'
      preLoaderRoute: typeof AppProductsBrandsIndexRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/app/products/categories/create': {
      id: '/app/products/categories/create'
      path: '/categories/create'
      fullPath: '/app/products/categories/create'
      preLoaderRoute: typeof AppProductsCategoriesCreateRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/app/products/brands/create': {
      id: '/app/products/brands/create'
      path: '/brands/create'
      fullPath: '/app/products/brands/create'
      preLoaderRoute: typeof AppProductsBrandsCreateRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
  }
}

interface AppProductsRouteRouteChildren {
  AppProductsIdRoute: typeof AppProductsIdRoute
  AppProductsCreateRoute: typeof AppProductsCreateRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppProductsBrandsCreateRoute: typeof AppProductsBrandsCreateRoute
  AppProductsCategoriesCreateRoute: typeof AppProductsCategoriesCreateRoute
  AppProductsBrandsIndexRoute: typeof AppProductsBrandsIndexRoute
  AppProductsCategoriesIndexRoute: typeof AppProductsCategoriesIndexRoute
}

const AppProductsRouteRouteChildren: AppProductsRouteRouteChildren = {
  AppProductsIdRoute: AppProductsIdRoute,
  AppProductsCreateRoute: AppProductsCreateRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppProductsBrandsCreateRoute: AppProductsBrandsCreateRoute,
  AppProductsCategoriesCreateRoute: AppProductsCategoriesCreateRoute,
  AppProductsBrandsIndexRoute: AppProductsBrandsIndexRoute,
  AppProductsCategoriesIndexRoute: AppProductsCategoriesIndexRoute,
}

const AppProductsRouteRouteWithChildren =
  AppProductsRouteRoute._addFileChildren(AppProductsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppProductsRouteRoute: typeof AppProductsRouteRouteWithChildren
  AppLocationsCreateRoute: typeof AppLocationsCreateRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppLocationsIndexRoute: typeof AppLocationsIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppRolesIndexRoute: typeof AppRolesIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProductsRouteRoute: AppProductsRouteRouteWithChildren,
  AppLocationsCreateRoute: AppLocationsCreateRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppLocationsIndexRoute: AppLocationsIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppRolesIndexRoute: AppRolesIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  InventoryRoute: InventoryRoute,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
