import createClient, { type Client } from "openapi-fetch";
import type { paths, components } from "./types.gen.js"; // generated by openapi-typescript
import { createProductsResource } from "./resources/products.js";
import { createCartResource } from "./resources/cart.js";
import { createCheckoutResource } from "./resources/checkout.js";

export type ProductListItem = components["schemas"]["ProductListItem"];
export type PaginatedProducts = components["schemas"]["PaginatedProducts"];
export type ProductDetail = components["schemas"]["ProductDetail"];
export type ProductDetailOption = components["schemas"]["ProductDetailOption"];
export type ProductDetailVariant = components["schemas"]["ProductDetailVariant"];
export type Cart = components["schemas"]["Cart"];
export type CartItem = components["schemas"]["CartItem"];
export type CheckoutSession = components["schemas"]["CheckoutSession"];
export type CheckoutConfig = components["schemas"]["CheckoutConfig"];
export type CheckoutSessionStatus = components["schemas"]["CheckoutSessionStatus"];

const APP_KEY_HEADER = "x-app-key";

export class StorefrontClient {
  appKey: string;
  // set automatically the first time cart.addItem() creates a cart — or
  // pass one in up front (e.g. restored from localStorage) to resume a cart
  cartToken: string | undefined;
  client: Client<paths>;

  products: ReturnType<typeof createProductsResource>;
  cart: ReturnType<typeof createCartResource>;
  checkout: ReturnType<typeof createCheckoutResource>;

  constructor(baseUrl: string, appKey: string, cartToken?: string) {
    this.appKey = appKey;
    this.cartToken = cartToken;
    this.client = createClient({ baseUrl });
    // the app key identifies the tenant on every request — read off `this`
    // rather than captured at construction, so reassigning `appKey` later
    // (e.g. switching storefronts) takes effect immediately
    this.client.use({
      onRequest: ({ request }) => {
        request.headers.set(APP_KEY_HEADER, this.appKey);
        return request;
      },
    });

    this.products = createProductsResource(this.client);
    this.cart = createCartResource(
      this.client,
      () => this.cartToken,
      (token) => {
        this.cartToken = token;
      },
    );
    this.checkout = createCheckoutResource(this.client, () => this.cartToken);
  }
}
