import createClient, { type Client } from "openapi-fetch";
import type { paths, components } from "./types.gen.js"; // generated by openapi-typescript
import { createProductsResource } from "./resources/products.js";

export type ProductListItem = components["schemas"]["ProductListItem"];
export type PaginatedProducts = components["schemas"]["PaginatedProducts"];
export type ProductDetail = components["schemas"]["ProductDetail"];
export type ProductDetailOption = components["schemas"]["ProductDetailOption"];
export type ProductDetailVariant = components["schemas"]["ProductDetailVariant"];

const APP_KEY_HEADER = "x-app-key";

export class StorefrontClient {
  appKey: string;
  client: Client<paths>;

  products: ReturnType<typeof createProductsResource>;

  constructor(baseUrl: string, appKey: string) {
    this.appKey = appKey;
    this.client = createClient({ baseUrl });
    // the app key identifies the tenant on every request — read off `this`
    // rather than captured at construction, so reassigning `appKey` later
    // (e.g. switching storefronts) takes effect immediately
    this.client.use({
      onRequest: ({ request }) => {
        request.headers.set(APP_KEY_HEADER, this.appKey);
        return request;
      },
    });

    this.products = createProductsResource(this.client);
  }
}
