/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProductListBrand: {
            id: number;
            name: string;
        };
        ProductListCategory: {
            id: number;
            name: string;
        };
        ProductListItem: {
            id: number;
            name: string;
            description: string | null;
            brand: components["schemas"]["ProductListBrand"] | null;
            categories: components["schemas"]["ProductListCategory"][];
            minPriceCents: number | null;
            maxPriceCents: number | null;
        };
        PaginatedProducts: {
            items: components["schemas"]["ProductListItem"][];
            total: number;
            limit: number;
            offset: number;
        };
        ProductDetailBrand: {
            id: number;
            name: string;
        };
        ProductDetailCategory: {
            id: number;
            name: string;
        };
        ProductDetailOptionValue: {
            id: number;
            value: string;
        };
        ProductDetailOption: {
            id: number;
            name: string;
            values: components["schemas"]["ProductDetailOptionValue"][];
        };
        VariantOptionValue: {
            optionName: string;
            value: string;
        };
        ProductDetailVariant: {
            id: number;
            sku: string | null;
            priceCents: number;
            stock: number;
            optionValues: components["schemas"]["VariantOptionValue"][];
        };
        ProductDetail: {
            id: number;
            name: string;
            description: string | null;
            brand: components["schemas"]["ProductDetailBrand"] | null;
            categories: components["schemas"]["ProductDetailCategory"][];
            options: components["schemas"]["ProductDetailOption"][];
            variants: components["schemas"]["ProductDetailVariant"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_findAll: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProducts"];
                };
            };
        };
    };
    ProductsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
