/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CartController_addItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CartController_getCart"];
        put?: never;
        post?: never;
        delete: operations["CartController_clear"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items/{variantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["CartController_removeItem"];
        options?: never;
        head?: never;
        patch: operations["CartController_updateItem"];
        trace?: never;
    };
    "/checkout/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CheckoutController_getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CheckoutController_createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout/shipping-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CheckoutController_getShippingOptions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout/session/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CheckoutController_getSessionStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProductListBrand: {
            id: number;
            name: string;
        };
        ProductListCategory: {
            id: number;
            name: string;
        };
        ProductListItem: {
            id: number;
            name: string;
            description: string | null;
            brand: components["schemas"]["ProductListBrand"] | null;
            categories: components["schemas"]["ProductListCategory"][];
            minPriceCents: number | null;
            maxPriceCents: number | null;
        };
        PaginatedProducts: {
            items: components["schemas"]["ProductListItem"][];
            total: number;
            limit: number;
            offset: number;
        };
        ProductDetailBrand: {
            id: number;
            name: string;
        };
        ProductDetailCategory: {
            id: number;
            name: string;
        };
        ProductDetailOptionValue: {
            id: number;
            value: string;
        };
        ProductDetailOption: {
            id: number;
            name: string;
            values: components["schemas"]["ProductDetailOptionValue"][];
        };
        VariantOptionValue: {
            optionName: string;
            value: string;
        };
        ProductDetailVariant: {
            id: number;
            sku: string | null;
            priceCents: number;
            stock: number;
            optionValues: components["schemas"]["VariantOptionValue"][];
        };
        ProductDetail: {
            id: number;
            name: string;
            description: string | null;
            brand: components["schemas"]["ProductDetailBrand"] | null;
            categories: components["schemas"]["ProductDetailCategory"][];
            options: components["schemas"]["ProductDetailOption"][];
            variants: components["schemas"]["ProductDetailVariant"][];
        };
        AddCartItemDto: {
            variantId: number;
            /** @default 1 */
            quantity: number;
        };
        CartItemOptionValue: {
            optionName: string;
            value: string;
        };
        CartItem: {
            variantId: number;
            productId: number;
            productName: string;
            sku: string | null;
            priceCents: number;
            quantity: number;
            stock: number;
            optionValues: components["schemas"]["CartItemOptionValue"][];
        };
        Cart: {
            token: string;
            items: components["schemas"]["CartItem"][];
            subtotalCents: number;
            itemCount: number;
        };
        UpdateCartItemDto: {
            quantity: number;
        };
        CheckoutConfig: {
            ready: boolean;
            stripeAccountId: string | null;
        };
        CreateCheckoutSessionDto: {
            returnUrl: string;
        };
        CheckoutSession: {
            clientSecret: string;
        };
        ShippingAddressDto: {
            country: string;
            line1?: string;
            line2?: string;
            city?: string;
            postal_code?: string;
            state?: string;
        };
        ShippingDetailsDto: {
            name: string;
            address: components["schemas"]["ShippingAddressDto"];
        };
        GetShippingOptionsDto: {
            checkoutSessionId: string;
            shippingDetails: components["schemas"]["ShippingDetailsDto"];
        };
        ShippingOptionsResult: {
            ok: boolean;
            errorMessage?: string;
        };
        CheckoutSessionStatus: {
            status: string;
            customerEmail: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_findAll: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProducts"];
                };
            };
        };
    };
    ProductsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CartController_addItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCartItemDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
        };
    };
    CartController_getCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CartController_clear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CartController_removeItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CartController_updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCartItemDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CheckoutController_getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutConfig"];
                };
            };
        };
    };
    CheckoutController_createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCheckoutSessionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSession"];
                };
            };
        };
    };
    CheckoutController_getShippingOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetShippingOptionsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShippingOptionsResult"];
                };
            };
        };
    };
    CheckoutController_getSessionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSessionStatus"];
                };
            };
        };
    };
}
